name: supabase-db

services:
  db:
    container_name: supabase-db
    image: supabase/postgres:15.8.1.085
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:5433
    volumes:
      # - ./data:/var/lib/postgresql/data
      - ../volumes/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
      # Must be superuser to create event trigger
      - ../volumes/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
      # Must be superuser to alter reserved role
      - ../volumes/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
      # Initialize the database settings with JWT_SECRET and JWT_EXP
      - ../volumes/db/jwt.sql:/docker-entrypoint-initdb.d/init-scripts/99-jwt.sql:Z
      # Changes required for internal supabase data such as _analytics
      - ../volumes/db/_supabase.sql:/docker-entrypoint-initdb.d/migrations/97-_supabase.sql:Z
      # Changes required for Analytics support
      - ../volumes/db/logs.sql:/docker-entrypoint-initdb.d/migrations/99-logs.sql:Z
      # Changes required for Pooler support
      - ../volumes/db/pooler.sql:/docker-entrypoint-initdb.d/migrations/99-pooler.sql:Z
      - ../volumes/data:/var/lib/postgresql
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${PANEL_DB_ROOT_USER}
      PGPASSWORD: ${PANEL_DB_ROOT_PASSWORD}
      POSTGRES_PASSWORD: ${PANEL_DB_ROOT_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXPIRY}
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-p", "5432", "-q", "-U", "${PANEL_DB_ROOT_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    command:
      [
        "postgres",
        "-c",
        "config_file=/etc/postgresql/postgresql.conf",
        # "-c",
        # "shared_buffers=64MB",
        # "-c",
        # "work_mem=4MB",
        "-c",
        "log_min_messages=fatal" # prevents Realtime polling queries from appearing in logs
      ]
    networks:
      - 1panel-network
      - supabase_network
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
  supabase_network:
    external: true
    name: supabase_network